language: cpp
matrix:
  include:
    - compiler: gcc
      env: PLATFORM=linux-gcc CXX=g++-4.9
      addons: {apt: {packages: [g++-4.9], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: PLATFORM=linux-gcc CXX=g++-5
      addons: {apt: {packages: [g++-5], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: PLATFORM=linux-gcc CXX=g++-6
      addons: {apt: {packages: [g++-6], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: PLATFORM=linux-gcc CXX=g++-7
      addons: {apt: {packages: [g++-7], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: PLATFORM=linux-gcc CXX=g++-8
      addons: {apt: {packages: [g++-8], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: PLATFORM=linux-gcc CXX=g++-9
      addons: {apt: {packages: [g++-9], sources: [ubuntu-toolchain-r-test]}}
    - compiler: clang
      env: PLATFORM=linux-clang CXX=clang++
    - os: osx
      env: PLATFORM=osx-clang CXX=clang++
    - os: windows
      env: PLATFORM=win-vs CXX=cl BITS=64
      before_install: choco install make --no-progress -y
env:
  - C_FLAGS=$(treat_warnings_as_errors)
script:
  - make -C tests compile
