name: Compile test

on: push

jobs:
  windows:
    name: Compile test on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        bits: [32, 64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win${{ matrix.bits }}

      - name: Install make
        run: choco install --no-progress -y make

      - name: Compile
        run: C:\ProgramData\Chocolatey\bin\make -k -C tests compile
        shell: cmd
        env:
          PLATFORM: win-vs
          BITS: ${{ matrix.bits }}
          C_FLAGS: "$(treat_warnings_as_errors)"

  linux:
    name: Compile test on Linux
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gcc: [g++-9, g++-10, g++-11]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: make -k -C tests compile
        env:
          PLATFORM: linux-gcc
          CXX: ${{ matrix.gcc }}
          C_FLAGS: "$(treat_warnings_as_errors)"

  macos:
    name: Compile test on macOS
    runs-on: macos-11
    strategy:
      matrix:
        clang: [clang++, "$(brew --prefix llvm@14)/bin/clang"]
        bits: [64, arm64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: make -k -C tests compile
        env:
          PLATFORM: osx-clang
          CXX: "${{ matrix.clang }}"
          BITS: ${{ matrix.bits }}
          C_FLAGS: "$(treat_warnings_as_errors)"
