name: Compile test

on: push

jobs:
  compile_test:
    name: Compile test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            flags: PLATFORM=linux-gcc CXX=g++-9
          - os: ubuntu-22.04
            flags: PLATFORM=linux-gcc CXX=g++-10
          - os: ubuntu-22.04
            flags: PLATFORM=linux-gcc CXX=g++-11
          - os: windows-2019
            flags: PLATFORM=win-vs BITS=32
          - os: windows-2019
            flags: PLATFORM=win-vs BITS=64
          - os: windows-2022
            flags: PLATFORM=win-vs BITS=32
          - os: windows-2022
            flags: PLATFORM=win-vs BITS=64
          - os: macos-11
            flags: PLATFORM=osx-clang BITS=64
          - os: macos-11
            flags: PLATFORM=osx-clang BITS=arm64

    steps:
      - uses: actions/checkout@v3

      - if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win${{ matrix.bits }}

      - if: startsWith(matrix.os, 'windows')
        name: Install make
        run: choco install --no-progress -y make

      - name: Compile
        run: make ${{ matrix.flags }} -k -C tests compile
        env:
          C_FLAGS: $(treat_warnings_as_errors)
